### ISSUE TITLE
Docsand System image  related to myagv jetson nano 2023

### ISSUE THREAD

**Issue by dineshkrishna9999** [elephantrobotics/myAGV-docs#4]
I could find only the system image link for only PI version of myAGV where could i find the system image of jetson nano version of myAGV ?
Could anyone help regarding it ?

**Comment by X-lanni** [comment]
> I could find only the system image link for only PI version of myAGV where could i find the system image of jetson nano version of myAGV ? Could anyone help regarding it ?

This is the system image [download link](https://download-elephantrobotics.oss-cn-shenzhen.aliyuncs.com/Product_software/iMage-ISO/myAGV/myAGV2023_ubuntu_V20240103_20.04JN_aarch64_shrunk.img.gz) for myagv JN 2023.The user manual for myagv JN 2023 will be updated in the GitHub project in the future.
